### ISSUE TITLE
run in android failed.

### ISSUE THREAD

**Issue by gaobaiq** [enwi/dartzmq#1]
Failed to load dynamic library 'liblibzmq-v142-mt-4_3_5.so': dlopen failed: library "liblibzmq-v142-mt-4_3_5.so" not found

**Comment by enwi** [comment]
For Android you need to support libzmq yourself. I have made some changes (which are not published yet), which support other dll/lib names other than `liblibzmq-v142-mt-4_3_5` (e.g. libzmq).

But essentially you need to follow [these steps](https://github.com/zeromq/libzmq/tree/master/builds/android), which will get you a `libzmq.so`. Which you need to include in your project following [these steps](https://github.com/truongsinh/flutter-ffi-samples/blob/master/packages/sqlite/docs/android.md#update-gradle-script)

**Comment by gaobaiq** [comment]
Very good. I'm trying to do the same. Now I build an so file and try to run the project.

**Comment by enwi** [comment]
> Very good. I'm trying to do the same. Now I build an so file and try to run the project.
Also for now you will need to rename `libzmq.so` to `libzmq-v142-mt-4_3_5.so`

**Comment by enwi** [comment]
Does it work for you? I am also trying to get a simple example running on Android, but it does not find/load the native library

**Comment by enwi** [comment]
Ahh so it seems `libc++_shared.so` is also needed for this to work
https://developer.android.com/ndk/guides/cpp-support#shared_runtimes
