### ISSUE TITLE
send non-binary data

### ISSUE THREAD

**Issue by NaarGes** [enwi/dartzmq#2]
Hi, why socket.send() parameter is from `List<int>` type? does it get data as binary array? what if someone wants to send data non-binary?

and I have another question; how we can receive response from a `req` socket connection?

**Comment by enwi** [comment]
Has this question been resolved for you @NaarGes ?

**Comment by NaarGes** [comment]
Actually I implement it bud I couldn't use it for my flutter application, It gets libzmq.so not found error (or sth like that) in runtime. I tried adding `libzmq.so` in my project using your hints from [#1 ] but still couldn't fix that error.
So because I have time limits, I switched using `jeromq` itself in Kotlin through `MethodChannel` and `EventChannel` in flutter.

**Comment by enwi** [comment]
Yeah getting it to work on Android is a little more difficult than on windows. For Android a compiled version of the standard c++ library is needed as well. I will need to add that to the documentation!

**Comment by NaarGes** [comment]
It's a very useful and unique package for dart. Keep it on!
good luck

**Comment by enwi** [comment]
I've updated the README and improved the steps for `Android`
