### ISSUE TITLE
Issues with library loading on Windows

### ISSUE THREAD

**Issue by chmoore889** [enwi/dartzmq#22]
When trying to use any these functions in my own code and the example code provided by this package, I'm having getting errors saying there are errors with loading the DLLs.
```
[dartzmq] Failed to load library zmq:  Invalid argument(s): Failed to load dynamic library 'zmq.dll': error code 126
[dartzmq] Failed to load library libzmq:  Invalid argument(s): Failed to load dynamic library 'libzmq.dll': error code 126
```

Based on the docs and what I've seen in other posted issues, I shouldn't need to do anything if I just want to use the default binaries. What am I doing wrong?

**Comment by chmoore889** [comment]
Printed errors were unrelated to actual issue

**Comment by enwi** [comment]
@chmoore889 Just to explain what was happening. Some `Failed to load Library` errors can just be ignored, because the code will try to load the library with platform dependant names and thus a few errors will be logged, even though the library was loaded correctly.
