### ISSUE TITLE
Incomplete data received by sub

### ISSUE THREAD

**Issue by gaobaiq** [enwi/dartzmq#3]
hi, did you find a problem? When subscribing to a topic under TCP protocol, big data will accept incompleteness, and I failed to set relevant properties.

**Comment by enwi** [comment]
I have not seen any issues so far and I am sending/receiving round about 0.5 MB/s of data.

With properties do you mean `option` (`setOption` function)? And which options were you not able to set?

**Comment by gaobaiq** [comment]
> I have not seen any issues so far and I am sending/receiving round about 0.5 MB/s of data.
> 
> With properties do you mean `option` (`setOption` function)? And which options were you not able to set?

I set the rcvbuf and rcvhwm properties.Now we have segmented the server transmission.It's okay, thank you.

**Comment by gaobaiq** [comment]
Also, do you know how to. / build.sh [ x86 ]，I failed to compile

**Comment by enwi** [comment]
> Also, do you know how to. / build.sh [ x86 ]，I failed to compile

Works for me just fine
