### ISSUE TITLE
on Linux with arm64 CUP，error

### ISSUE THREAD

**Issue by dingjianjaja** [enwi/dartzmq#41]
![image](https://github.com/user-attachments/assets/afe895d2-54f7-41a5-b7af-ad9759f4a15d)
how can I solve this problem ，Thanks♪(･ω･)ﾉ

**Comment by enwi** [comment]
It seems like the compiled version of zeromq is not built with poller support

**Comment by dingjianjaja** [comment]
Thanks your reply, could you tell me how to build the compiled version of zeromq with poller support?

**Comment by enwi** [comment]
Did you follow theses steps?
https://github.com/enwi/dartzmq/issues/8#issuecomment-1189366083

**Comment by enwi** [comment]
@dingjianjaja Did you get it working?

**Comment by rbebb** [comment]
@dingjianjaja Just checking to see if you got it working (cc @enwi)
