### ISSUE TITLE
Brain-free installation

### ISSUE THREAD

**Issue by Eerey** [enwi/dartzmq#5]
I know it's kind of a huge task, but would it be **theoretically** possible to use ZeroMQ in Flutter without thinking about Android/Windows/iOS/Linux?

What steps would be necessary?

Would it be possible to distribute precompiled zeromq-Versions (.dll, .so etc) within this plugin?

Is it theoretically possible to transpile the ZeroMQ Code to Dart only?

We think this is an amazing plugin but we're really uncertain about the fact that you need to make sure that e.g. a precompiled .dll (windows) works on every machine (it does not).

**Comment by Scylla2020** [comment]
I been struggling for hours trying to understand how creating a shared dll on windows works. It sounded like something that should be straightforward seeing the steps were omitted from the docs. Would you be able to share what exact steps to follow to create the shared dll for Windows 10? Like what file do we need to download from where, what commands are used to create the dll etc. Looks like an awesome plugin would love to get it to work. Thank you

**Comment by Eerey** [comment]
In my case, I did not compile it myself. I downloaded it somewhere and renamed it to the expected file name.
This can be optimized in many ways and I struggled to find that out myself aswell.

**Comment by enwi** [comment]
@Scylla2020 
You can find some instructions [here](https://github.com/zeromq/libzmq/blob/master/INSTALL)

**Comment by Scylla2020** [comment]
Oh great thanks let me have a look at the instructions,

**Comment by kevinelliott** [comment]
I don't use Flutter. I was disappointed that I couldn't use this library since I'm Dart-only.

**Comment by enwi** [comment]
@kevinelliott Technically this should be possible, since there aren't any dependencies to Flutter afaik.

**Comment by kevinelliott** [comment]
> @kevinelliott Technically this should be possible, since there aren't any dependencies to Flutter afaik.

The fact that it currently requires flutter lib prevents this at the moment. Is there any way to allow for dart only?

**Comment by enwi** [comment]
I think it should be possible to convert this into a dart only package, though how would the different compiled libraries for different platforms be handled?

**Comment by enwi** [comment]
Me too

**Comment by rbebb** [comment]
Is there any news on this effort? It would be so cool to have this as a Dart only package!

**Comment by One-Nub** [comment]
> I have seen packages listed that support both SDKs. I wonder how they do it.

Just from skimming pubspec.yaml(s), this is usually just accomplished automatically by the site when a file only uses the [SDK constraint](https://dart.dev/tools/pub/pubspec#sdk-constraints) under the environment field (so thus not requiring flutter). In the case of this package, I'm not sure how that would affect the other dependencies (specifically the dev_dependencies). I would guess removing flutter specific stuff would work in this case, but would just have to try it and see what happens.

**Comment by kevinelliott** [comment]
Any update here?

**Comment by enwi** [comment]
I haven't had time to take a deeper look into this, but this might change in the upcoming days. I would also like to check if the changes in #4 improve the overall performance.

**Comment by kevinelliott** [comment]
Is there an easy way for me to override this in my own project so that I can at least move forward with development?

**Comment by enwi** [comment]
You can change the source code locally. If you use VS-Code it will display a warning, but until you update the dependencies and there is a new release of this library you should be fine.

**Comment by Eerey** [comment]
> Is there any news on this effort? It would be so cool to have this as a Dart only package!

According to stackoverflow answers, it would also be possible to do it in dart only:
https://stackoverflow.com/questions/71127181/mimic-zeromq-sub-socket-in-a-pub-sub-system-with-e-g-socket-websocket-in-flut

**Comment by enwi** [comment]
@kevinelliott I removed the flutter dependencies, if you want you can try the new version

**Comment by enwi** [comment]
@Eerey @Scylla2020 it should now work for Windows and Android out of the box

**Comment by enwi** [comment]
@kevinelliott @rbebb @One-Nub With the change now the issue is that I have to include the Flutter dependency otherwise it does not work. It won't le me publish the package without it, because the `platforms` key requires it. I wonder if there is a solution for this. Other than that if you provide the `ZeroMQ` binary yourself it should work with dart only with a298137968251477faa6ecd759db32a3ed518800
```dart
plugin:
    platforms:
```

**Comment by enwi** [comment]
So we either need to find a workaround for the `platforms` key or we could split the code into two repositories, one with all the dart only code and one for flutter where it automatically includes the binaries

**Comment by kevinelliott** [comment]
I wonder if someone at https://github.com/dart-lang or https://github.com/flutter could chime in with the best practice here.

**Comment by Scylla2020** [comment]
@enwi Thanks for this! I'll give it a go
