### ISSUE TITLE
Failed to load dynamic library issue on MacOS platform

### ISSUE THREAD

**Issue by richsi** [enwi/dartzmq#9]
Hello,

I have been trying to use dartzmq on flutter to establish a connection to a remote server host, but I keep getting the error:

`[dartzmq] Failed to load library zmq:  Invalid argument(s): Failed to load dynamic library 'libzmq.so': dlopen failed: library "libzmq.so" not found`
`[dartzmq] Failed to load library libzmq:  Invalid argument(s): Failed to load dynamic library 'liblibzmq.so': dlopen failed: library "liblibzmq.so" not found`
`[dartzmq] Failed to load library libzmq-v142-mt-4_3_5:  Invalid argument(s): Failed to load dynamic library 'liblibzmq-v142-mt-4_3_5.so': dlopen failed: library "liblibzmq-v142-mt-4_3_5.so" not found`

I have built the MacOS platform in my local dartzmq repo and linked it to my flutter app. I was wondering if anyone could help me debug this library issue? If someone has dealt with this problem before, a simple list of steps to fix it would be much appreciated. Thanks!

**Comment by enwi** [comment]
Hey @richsi MacOS is currently not officially supported. In order to make it work you will have to compile ZeroMQ yourself or get a precompiled binary for MacOS and put it next to your flutter executable. Since I don't have any Apple Device I can't help you here.

**Comment by enwi** [comment]
Maybe you could try the linux instructions that have worked so far -> https://github.com/enwi/dartzmq/issues/8#issuecomment-1189366083

**Comment by richsi** [comment]
Hi enwi,

I am trying to build libzmq for android and I am currently following the first step to get libzmq.so
Do you know how to get the readelf file into the bin? I can't build with any other archs either

<img width="808" alt="image" src="https://user-images.githubusercontent.com/99142018/186484016-2956ab85-3ec9-4435-9a18-a1e8ed0c86de.png">
